### PR TITLE
Add support for DRF >= 3.7.7., Django >= 1.11, taggit >=0.22, python 3.6

### PR DESCRIPTION
**Pull request by andrlik**
Enables use of DRF 3.7.7 and 3.8
Enables Django >= 1.11 while maintaining backwards compatibility.
Adds testing support for 3.6
Tweaks Travis build matrix to ensure that DRF versions are only being testing against their compatible Django versions.

### CODE REVIEW

**Comment by glemmaPaul** [comment]
This looks great, thank you very much for you contribution! I'm going to bump the version and get it merged.

**Comment by andrlik** [comment]
Glad to help! Any updates on the version bump?

**Comment by andrlik** [comment]
Any updates on the version bump?

**Comment by glemmaPaul** [comment]
Hey @andrlik first of all apologies for the late response, but I finally got to it, thanks for the notifications they helped me get reminded

Version 0.1.7 is available now! Thank you very much for the contributions 🎉

**Pull request merged**
