### PR TITLE
order_by property

### PR DESCRIPTION
**Pull request by tpeaton**
This adds an 'order_by' property that can be overriden to specify a custom ordering for tags.  The default is `['id']`.

Example:

```
class SortedTagSerializer(TagListSerializerField):
    order_by = ['name']


class SomeSerializer(TaggitSerializer, ModelSerializer):
    tags = SortedTagSerializer()
```

I haven't been able to get the tests to run locally yet as outlined in [the docs](https://github.com/glemmaPaul/django-taggit-serializer/blob/master/CONTRIBUTING.rst#get-started).  (But it looks like they worked fine on Travis)

### CODE REVIEW

**Comment by glemmaPaul** [comment]
Thanks for the PR @tpeaton, I would love to add this option, but I don't think a default to `id` is a good idea. This may be because people already order on something else. What do you think?

**Comment by tpeaton** [comment]
Yea, I have mixed feelings about it as well.  I was trying to avoid it, but it probably makes more sense to do an `if` block and only apply the ordering if `order_by` is specified.  If you agree, I'll push up that change.

**Comment by glemmaPaul** [comment]
@tpeaton That sounds like a good idea yes! Could you (not necessarily needed) rebase the PR to one commit too?

**Comment by tpeaton** [comment]
Sure thing, thanks.

**Comment by glemmaPaul** [comment]
Merging this in, will be in the next release! Thanks for the great contribution! :+1:

**Comment by tpeaton** [comment]
Awesome, thanks!

**Pull request merged**
